### ISSUE TITLE
not sure its an issue just wanted to show u :)

### ISSUE THREAD

**Issue by bobzen1234** [theBGuy/Kolbot-SoloPlay#8] opened 2021-09-03 23:54 UTC
Not sure this is an issue but i got this error once.
Really nice bot tho testing it on a hammerdin now and got 1-13 in 1 hour and 26 minutes so far :)

Error in SoloPlay (prototypes.js #303) Unit.drop: Must be used with items. (Area: 1, Ping:62, Game: ******

**Comment by bobzen1234** [comment] 2021-09-04 00:02
Also one more question. Is it possible to use custom pickit files for my profile? :) if yes where do i write them in? :)

**Comment by theBGuy** [comment] 2021-09-04 00:09
You can add your pickit file to whatever default config, so if you're running a sorceress, add it to Sorceress.SoloPlay inside that file. As for the error I've seen that a couple times only happen once while the bots just starting out. Ive been trying to find the cause by ty I appreciate it!

**Comment by bobzen1234** [comment] 2021-09-04 17:04
> You can add your pickit file to whatever default config, so if you're running a sorceress, add it to Sorceress.SoloPlay inside that file. As for the error I've seen that a couple times only happen once while the bots just starting out. Ive been trying to find the cause by ty I appreciate it!

Okay awesome and thanks for the quick reply! :)
woke up this morning and saw that the bot had crashed a bunch of times but i closed and launched the kolbot program itself and it have ran for 2-3 hours now without a crash so far :)

Will keep reporting back if i find any errors or potential updates to the bot :)

Also once again thanks for this awesome bot! :)

**Comment by bobzen1234** [comment] 2021-09-04 17:06
Also one more question.

Should i enable auto mule for the bot or will it clear stash for unwanted items itself and only keep items worth keeping? eg sojs, hrs other goodies and such?

**Comment by theBGuy** [comment] 2021-09-04 17:31
> > You can add your pickit file to whatever default config, so if you're running a sorceress, add it to Sorceress.SoloPlay inside that file. As for the error I've seen that a couple times only happen once while the bots just starting out. Ive been trying to find the cause by ty I appreciate it!
> 
> Okay awesome and thanks for the quick reply! :)
> woke up this morning and saw that the bot had crashed a bunch of times but i closed and launched the kolbot program itself and it have ran for 2-3 hours now without a crash so far :)
> 
> Will keep reporting back if i find any errors or potential updates to the bot :)
> 
> Also once again thanks for this awesome bot! :)

Can you explain what you mean by a bunch of times? I few crashes is normal, my crash rate hovers around 4-7 % and its due to the bot trying to leave the game, while also trying to townchicken. 

> Also one more question.
> 
> Should i enable auto mule for the bot or will it clear stash for unwanted items itself and only keep items worth keeping? eg sojs, hrs other goodies and such?

As for automule, the bot will clear the stash of any unwanted items, selling them if it can. It will only keep vex and above for runes by default otherwise if you added a pickit file I would enable automule. Without it, the bots stash will fill and it'll break. A note on that though is it will slow down the bots progress.

**Comment by bobzen1234** [comment] 2021-09-04 20:23
> > > You can add your pickit file to whatever default config, so if you're running a sorceress, add it to Sorceress.SoloPlay inside that file. As for the error I've seen that a couple times only happen once while the bots just starting out. Ive been trying to find the cause by ty I appreciate it!
> > 
> > 
> > Okay awesome and thanks for the quick reply! :)
> > woke up this morning and saw that the bot had crashed a bunch of times but i closed and launched the kolbot program itself and it have ran for 2-3 hours now without a crash so far :)
> > Will keep reporting back if i find any errors or potential updates to the bot :)
> > Also once again thanks for this awesome bot! :)
> 
> Can you explain what you mean by a bunch of times? A few crashes is normal, my crash rate hovers around 4-7 % and its due to the bot trying to leave the game, while also trying to townchicken.
> 
> > Also one more question.
> > Should i enable auto mule for the bot or will it clear stash for unwanted items itself and only keep items worth keeping? eg sojs, hrs other goodies and such?
> 
> As for automule, the bot will clear the stash of any unwanted items, selling them if it can. It will only keep vex and above for runes by default otherwise if you added a pickit file I would enable automule. Without it, the bots stash will fill and it'll break. A note on that though is it will slow down the bots progress.

Overnight i would say about 8 hours it crashed 12 times but seems to have stopped now :) i havent added a custom pickit yet and the stash is almost full with some items i think it kept for making runewords. Will it sell these items later or should i just drop  them myself? since it goes to town quite often now to make room for items on ground :)

**Comment by theBGuy** [comment] 2021-09-09 17:07
Just pushed a fix for the Unit.drop: Must be used with items

**Closed by theBGuy** 2021-09-09 17:07 UTC
